### ISSUE TITLE
Shallow Blue Chess for Windows

### ISSUE THREAD

**Issue by ChessGUI** [GunshipPenguin/shallow-blue#13]
Hello Gunship Penguin,

I noticed on GitHub a new version of Shallow Blue . but without Windows binaries (I possess Windows 7 SP1 32-/64 bit).

Could you create a working Shallow Blue  edition for Windows systems, please? My computer (ivy-bridge-22nm structure)  supports the features AVX, POPCNT of course but not .BMI2 (=Haswell component).

By the way: https://drive.google.com/file/d/0B-PM8aD2-9I4ZUZYRWQ5blM0bWc/view is another chess engine by Dmitry Sultanov that  is called "Shallow2" too. https://github.com/dimock/chess

Best wishes,

**Comment by GunshipPenguin** [comment]
Hi There,

I'm working on setting up MinGW-w64 to compile Shallow Blue for Windows. I will be including Windows binaries from the next release onwards.

Here's a zip containing a MinGW build of Shallow Blue for 64 bit. Tested and working under Wine and Windows 10 x64. Let me know if it works for you.

[shallowblue.zip](https://github.com/GunshipPenguin/shallow-blue/files/1144108/shallowblue.zip)

**Comment by ChessGUI** [comment]
The downloaded application shallowblue.zip crashed immediately on my Windows 7 64-bit SP1 system after extraction; perhaps it is a BMI.2-executable file that does not work on an Ivy-Bridge-computer

Did you use https://sourceforge.net/projects/mingw-w64/ for this purpose?

**Comment by GunshipPenguin** [comment]
I was using the `-march=native` flag when compiling and have a Haswell CPU, so that could very well be it.

I've recompiled without the `-march=native` flag. Here is the new zip. Note that this is a bit slower than Shallow Blue compiled with `-march=native` (about 20% or so).

[shallowblue.zip](https://github.com/GunshipPenguin/shallow-blue/files/1144286/shallowblue.zip)

**Comment by ChessGUI** [comment]
it runs now on Arena GUI www.playwitharena.com - which of the following instructions are at least required by the CPU?: MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX, VMX, AES, AVX
cf. **Speccy** https://www.piriform.com/speccy
for upcoming Windows editions it would be a good idea to create several .exe-files
e.g. for Haswell BMI.2, SSE4.2, AVX, POPCNT

**Comment by GunshipPenguin** [comment]
In its current state, Shallow Blue doesn't take heavy advantage of BMI2 / AVX / SSE instructions. Because of this, I've decided to just build the Windows binaries with `-mtune=generic`. This could change in the future if I optimize Shallow Blue for these instructions.

MinGW binaries have now been uploaded to the 1.0.1 release and will be uploaded for all future releases.
